export type SeedGeneralListItem = {
  itemKey: string;
  nameEs: string;
  nameEn: string;
  category: string;
  quantity: string;
  unit: string;
  store: string;
  active: boolean;
};

export const SEED_GENERAL_ITEMS: SeedGeneralListItem[] = [
  { itemKey: "garlic", nameEs: "Ajo", nameEn: "Garlic", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "broccoli", nameEs: "Brocoli", nameEn: "Broccoli", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "onion", nameEs: "Cebolla", nameEn: "Onion", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "lettuce", nameEs: "Lechuga", nameEn: "Lettuce", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "potatoes", nameEs: "Papas", nameEn: "Potatoes", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "cucumber", nameEs: "Pepino", nameEn: "Cucumber", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "peppers", nameEs: "Pimientos", nameEn: "Peppers", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "cabbage", nameEs: "Repollo", nameEn: "Cabbage", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "tomatoes", nameEs: "Tomates", nameEn: "Tomatoes", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "carrots", nameEs: "Zanahoria", nameEn: "Carrots", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "banana", nameEs: "Banana", nameEn: "Banana", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "lime", nameEs: "Limón", nameEn: "Lime", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "apple", nameEs: "Manzana", nameEn: "Apple", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "melon", nameEs: "Melón", nameEn: "Melon", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "orange", nameEs: "Naranja", nameEn: "Orange", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "papaya", nameEs: "Papaya", nameEn: "Papaya", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "pear", nameEs: "Pera", nameEn: "Pear", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "pineapple", nameEs: "Piña", nameEn: "Pineapple", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "watermelon", nameEs: "Sandía", nameEn: "Watermelon", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "beef", nameEs: "Carne de Res", nameEn: "Beef", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "deli-meats", nameEs: "Embutidos", nameEn: "Deli Meats", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "fish", nameEs: "Pescado", nameEn: "Fish", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "chicken", nameEs: "Pollo", nameEn: "Chicken", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "pork", nameEs: "Puerco/Cerdo", nameEn: "Pork", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "sausages", nameEs: "Salchichas", nameEn: "Sausages", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "salmon", nameEs: "Salmón", nameEn: "Salmon", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "bacon", nameEs: "Tocino", nameEn: "Bacon", category: "Carnes, Pollo y Pescados", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "rice", nameEs: "Arroz", nameEn: "Rice", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "sugar", nameEs: "Azúcar", nameEn: "Sugar", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "cereal", nameEs: "Cereal", nameEn: "Cereal", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "cookies", nameEs: "Galletas", nameEn: "Cookies", category: "Abarrotes", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "gelatin", nameEs: "Gelatina", nameEn: "Gelatin", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "corn-flour", nameEs: "Harina de Maíz", nameEn: "Corn Flour", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "wheat-flour", nameEs: "Harina de Trigo", nameEn: "Wheat Flour", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { itemKey: "pancake-mix", nameEs: "Mezcla Pancakes", nameEn: "Pancake Mix", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "nuts", nameEs: "Nueces", nameEn: "Nuts", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "raisins", nameEs: "Pasas", nameEn: "Raisins", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "bread", nameEs: "Pan", nameEn: "Bread", category: "Panadería y Tortillería", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "pasta", nameEs: "Pasta", nameEn: "Pasta", category: "Abarrotes", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "popcorn", nameEs: "PopCorn", nameEn: "Popcorn", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "mashed-potatoes", nameEs: "Puré de papas", nameEn: "Mashed Potatoes", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "snacks", nameEs: "Snacks", nameEn: "Snacks", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "vanilla", nameEs: "Vainilla", nameEn: "Vanilla", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "milk", nameEs: "Leche", nameEn: "Milk", category: "Lácteos y Refrigerados", quantity: "1", unit: "l", store: "", active: true },
  { itemKey: "butter", nameEs: "Mantequilla", nameEn: "Butter", category: "Lácteos y Refrigerados", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "cheese", nameEs: "Queso", nameEn: "Cheese", category: "Lácteos y Refrigerados", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "yogurt", nameEs: "Yogurt", nameEn: "Yogurt", category: "Lácteos y Refrigerados", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "eggs", nameEs: "Huevos", nameEn: "Eggs", category: "Lácteos y Refrigerados", quantity: "1", unit: "docena", store: "", active: true },
  { itemKey: "ice-cream", nameEs: "Helado", nameEn: "Ice Cream", category: "Congelados", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "red-beans", nameEs: "Frijoles Rojos", nameEn: "Red Beans", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "black-beans", nameEs: "Frijoles Negros", nameEn: "Black Beans", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "chickpeas", nameEs: "Garbanzos", nameEn: "Chickpeas", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "lentils", nameEs: "Lenteja", nameEn: "Lentils", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "corn", nameEs: "Maíz", nameEn: "Corn", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "oil", nameEs: "Aceite", nameEn: "Oil", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "olive-oil", nameEs: "Aceite de Oliva", nameEn: "Olive Oil", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "salad-dressing", nameEs: "Aderezo Ensaladas", nameEn: "Salad Dressing", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "ketchup", nameEs: "Ketchup", nameEn: "Ketchup", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "peanut-butter", nameEs: "Mantequilla de Maní", nameEn: "Peanut Butter", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "mayonnaise", nameEs: "Mayonesa", nameEn: "Mayonnaise", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "honey", nameEs: "Miel", nameEn: "Honey", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "mustard", nameEs: "Mostaza", nameEn: "Mustard", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "soy-sauce", nameEs: "Salsa de Soya", nameEn: "Soy Sauce", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "maple-syrup", nameEs: "Sirope de Maple", nameEn: "Maple Syrup", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "vinegar", nameEs: "Vinagre", nameEn: "Vinegar", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "tuna", nameEs: "Atún", nameEn: "Tuna", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "beans", nameEs: "Frijoles", nameEn: "Beans", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "fruit-cocktail", nameEs: "Frutas Cocktail", nameEn: "Fruit Cocktail", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "whole-corn", nameEs: "Maíz entero", nameEn: "Whole Corn", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "sardines", nameEs: "Sardinas", nameEn: "Sardines", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "soup", nameEs: "Sopa", nameEn: "Soup", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "canned-tomatoes", nameEs: "Tomates en lata", nameEn: "Canned Tomatoes", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "mixed-vegetables", nameEs: "Vegetales Mixtos", nameEn: "Mixed Vegetables", category: "Congelados", quantity: "1", unit: "lata", store: "", active: true },
  { itemKey: "cat-litter", nameEs: "Arena para gato", nameEn: "Cat Litter", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "cat-food", nameEs: "Comida para gato", nameEn: "Cat Food", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "bird-food", nameEs: "Comida para pájaros", nameEn: "Bird Food", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "dog-food", nameEs: "Comida para perro", nameEn: "Dog Food", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "pet-medicine", nameEs: "Medicinas", nameEn: "Pet Medicine", category: "Mascotas", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "training-pads", nameEs: "Pads entrenamiento", nameEn: "Training Pads", category: "Mascotas", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "pet-shampoo", nameEs: "Shampoo", nameEn: "Pet Shampoo", category: "Mascotas", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "water", nameEs: "Agua", nameEn: "Water", category: "Bebidas", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "coffee", nameEs: "Café", nameEn: "Coffee", category: "Bebidas", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "beer", nameEs: "Cerveza", nameEn: "Beer", category: "Bebidas", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "orange-juice", nameEs: "Jugo Naranja", nameEn: "Orange Juice", category: "Bebidas", quantity: "1", unit: "l", store: "", active: true },
  { itemKey: "fruit-juice", nameEs: "Jugo Frutas", nameEn: "Fruit Juice", category: "Bebidas", quantity: "1", unit: "l", store: "", active: true },
  { itemKey: "liquor", nameEs: "Licor", nameEn: "Liquor", category: "Bebidas", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "soda", nameEs: "Soda/Gaseosa", nameEn: "Soda", category: "Bebidas", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "tea", nameEs: "Te", nameEn: "Tea", category: "Bebidas", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "wine", nameEs: "Vino", nameEn: "Wine", category: "Bebidas", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "salt", nameEs: "Sal", nameEn: "Salt", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "garlic-powder", nameEs: "Ajo en Polvo", nameEn: "Garlic Powder", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "cinnamon", nameEs: "Canela", nameEn: "Cinnamon", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "cumin", nameEs: "Comino", nameEn: "Cumin", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "chicken-bouillon", nameEs: "Cubito de pollo", nameEn: "Chicken Bouillon", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "beef-bouillon", nameEs: "Cubito de carne", nameEn: "Beef Bouillon", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "fine-herbs", nameEs: "Finas Hierbas", nameEn: "Fine Herbs", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "bay-leaves", nameEs: "Hojas de Laurel", nameEn: "Bay Leaves", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "oregano", nameEs: "Oregano", nameEn: "Oregano", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "pepper", nameEs: "Pimienta", nameEn: "Pepper", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "seasoning", nameEs: "Sazonador", nameEn: "Seasoning", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { itemKey: "resealable-bags", nameEs: "Bolsas sellables", nameEn: "Resealable Bags", category: "Limpieza y Hogar", quantity: "1", unit: "caja", store: "", active: true },
  { itemKey: "aluminum-foil", nameEs: "Papel Aluminio", nameEn: "Aluminum Foil", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { itemKey: "wax-paper", nameEs: "Papel Encerado", nameEn: "Wax Paper", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { itemKey: "toilet-paper", nameEs: "Papel Higiénico", nameEn: "Toilet Paper", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "paper-towels", nameEs: "Papel Toalla", nameEn: "Paper Towels", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "plastic-wrap", nameEs: "Plástico Envolver", nameEn: "Plastic Wrap", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { itemKey: "napkins", nameEs: "Servilletas", nameEn: "Napkins", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "soap", nameEs: "Jabón", nameEn: "Soap", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "shampoo", nameEs: "Shampoo", nameEn: "Shampoo", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "conditioner", nameEs: "Acondicionador", nameEn: "Conditioner", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "razors", nameEs: "Razuradoras", nameEn: "Razors", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "shaving-cream", nameEs: "Crema afeitar", nameEn: "Shaving Cream", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "deodorant", nameEs: "Desodorante", nameEn: "Deodorant", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "body-lotion", nameEs: "Crema Corporal", nameEn: "Body Lotion", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "toothpaste", nameEs: "Pasta Dental", nameEn: "Toothpaste", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "dental-floss", nameEs: "Hilo Dental", nameEn: "Dental Floss", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { itemKey: "mouthwash", nameEs: "Enjuague Bucal", nameEn: "Mouthwash", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "bleach", nameEs: "Blanqueador", nameEn: "Bleach", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "trash-bags", nameEs: "Bolsas de basura", nameEn: "Trash Bags", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { itemKey: "disinfectant", nameEs: "Desinfectante", nameEn: "Disinfectant", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "detergent", nameEs: "Detergentes", nameEn: "Detergent", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "sponges", nameEs: "Esponjas", nameEn: "Sponges", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "dish-soap", nameEs: "Jabón lavaplatos", nameEn: "Dish Soap", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { itemKey: "laundry-detergent", nameEs: "Jabón para ropa", nameEn: "Laundry Detergent", category: "Limpieza y Hogar", quantity: "1", unit: "bolsa", store: "", active: true },
  { itemKey: "wipes", nameEs: "Pañitos", nameEn: "Wipes", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { itemKey: "wet-wipes", nameEs: "Toallas Húmedas", nameEn: "Wet Wipes", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
];
