export type SeedGeneralListItem = {
  name: string;
  category: string;
  quantity: string;
  unit: string;
  store: string;
  active: boolean;
};

export const SEED_GENERAL_ITEMS: SeedGeneralListItem[] = [
  { name: "Ajo", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Brocoli", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Cebolla", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Lechuga", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Papas", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Pepino", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Pimientos", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Repollo", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Tomates", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Zanahoria", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Banana", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Limón", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Manzana", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Melón", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Naranja", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Papaya", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Pera", category: "Frutas y Verduras", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Piña", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Sandía", category: "Frutas y Verduras", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Carne de Res", category: "Lácteos y Refrigerados", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Embutidos", category: "Lácteos y Refrigerados", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Pescado", category: "Lácteos y Refrigerados", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Pollo", category: "Lácteos y Refrigerados", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Puerco/Cerdo", category: "Lácteos y Refrigerados", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Salchichas", category: "Lácteos y Refrigerados", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Salmón", category: "Lácteos y Refrigerados", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Tocino", category: "Lácteos y Refrigerados", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Arroz", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Azúcar", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Cereal", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Galletas", category: "Abarrotes", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Gelatina", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Harina de Maíz", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Harina de Trigo", category: "Abarrotes", quantity: "1", unit: "kg", store: "", active: true },
  { name: "Mezcla Pancakes", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Nueces", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Pasas", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Pan", category: "Abarrotes", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Pasta", category: "Abarrotes", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "PopCorn", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Puré de papas", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Snacks", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Vainilla", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Leche", category: "Lácteos y Refrigerados", quantity: "1", unit: "l", store: "", active: true },
  { name: "Mantequilla", category: "Lácteos y Refrigerados", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Queso", category: "Lácteos y Refrigerados", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Yogurt", category: "Lácteos y Refrigerados", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Huevos", category: "Lácteos y Refrigerados", quantity: "1", unit: "docena", store: "", active: true },
  { name: "Helado", category: "Lácteos y Refrigerados", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Frijoles Rojos", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Frijoles Negros", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Garbanzos", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Lenteja", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Maíz", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Aceite", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Aceite de Oliva", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Aderezo Ensaladas", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Ketchup", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Mantequilla de Maní", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Mayonesa", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Miel", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Mostaza", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Salsa de Soya", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Sirope de Maple", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Vinagre", category: "Abarrotes", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Atún", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Frijoles", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Frutas Cocktail", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Maíz entero", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Sardinas", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Sopa", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Tomates en lata", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Vegetales Mixtos", category: "Abarrotes", quantity: "1", unit: "lata", store: "", active: true },
  { name: "Arena para gato", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Comida para gato", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Comida para pájaros", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Comida para perro", category: "Mascotas", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Medicinas", category: "Mascotas", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Pads entrenamiento", category: "Mascotas", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Shampoo", category: "Mascotas", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Agua", category: "Bebidas", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Café", category: "Bebidas", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Cerveza", category: "Bebidas", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Jugo Naranja", category: "Bebidas", quantity: "1", unit: "l", store: "", active: true },
  { name: "Jugo Frutas", category: "Bebidas", quantity: "1", unit: "l", store: "", active: true },
  { name: "Licor", category: "Bebidas", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Soda/Gaseosa", category: "Bebidas", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Te", category: "Bebidas", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Vino", category: "Bebidas", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Sal", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Ajo en Polvo", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Canela", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Comino", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Cubito de pollo", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Cubito de carne", category: "Abarrotes", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Finas Hierbas", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Hojas de Laurel", category: "Abarrotes", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Oregano", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Pimienta", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Sazonador", category: "Abarrotes", quantity: "1", unit: "frasco", store: "", active: true },
  { name: "Bolsas sellables", category: "Limpieza y Hogar", quantity: "1", unit: "caja", store: "", active: true },
  { name: "Papel Aluminio", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { name: "Papel Encerado", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { name: "Papel Higiénico", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Papel Toalla", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Plástico Envolver", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { name: "Servilletas", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Jabón", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Shampoo", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Acondicionador", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Razuradoras", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Crema afeitar", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Desodorante", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Crema Corporal", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Pasta Dental", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Hilo Dental", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "pza", store: "", active: true },
  { name: "Enjuague Bucal", category: "Farmacia, Bebé y Cuidado Personal", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Blanqueador", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Bolsas de basura", category: "Limpieza y Hogar", quantity: "1", unit: "rollo", store: "", active: true },
  { name: "Desinfectante", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Detergentes", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Esponjas", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Jabón lavaplatos", category: "Limpieza y Hogar", quantity: "1", unit: "botella", store: "", active: true },
  { name: "Jabón para ropa", category: "Limpieza y Hogar", quantity: "1", unit: "bolsa", store: "", active: true },
  { name: "Pañitos", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
  { name: "Toallas Húmedas", category: "Limpieza y Hogar", quantity: "1", unit: "paquete", store: "", active: true },
];
